# Generated by Django 4.2.11 on 2024-03-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usetname', models.CharField(max_length=122)),
                ('Email', models.CharField(max_length=122)),
                ('createPassword', models.CharField(max_length=8)),
            ],
        ),
    ]
