# Generated by Django 4.2.11 on 2024-04-04 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sing',
            new_name='login',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='createPassword',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='usetname',
            new_name='name',
        ),
    ]
